# Generated by Django 4.2.17 on 2025-01-02 14:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactSubmission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('todaysDate', models.DateField(auto_now_add=True, null=True)),
                ('name', models.CharField(default='N/A', max_length=20)),
                ('email', models.EmailField(default='', max_length=20)),
                ('subject', models.CharField(default='', max_length=50)),
                ('message', models.TextField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Module',
            fields=[
                ('name', models.CharField(default='', max_length=100, primary_key=True, serialize=False)),
                ('Course_Code', models.CharField(default='0000', max_length=50)),
                ('credits', models.IntegerField(default=0)),
                ('category', models.BooleanField(choices=[('compulsary', 'compulsary'), ('voluntary', 'voluntary')], default='voluntary')),
                ('Description', models.TextField(default='', max_length=200)),
                ('Course', models.CharField(default='', max_length=100)),
                ('avalaible', models.BooleanField(choices=[('Yes', 'Yes'), ('No', 'No')], default='Yes')),
            ],
        ),
        migrations.CreateModel(
            name='Registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('registration_time', models.DateField(auto_now_add=True, null=True)),
                ('Module', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='management.module')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('name', models.CharField(default='', max_length=40, primary_key=True, serialize=False)),
                ('module', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='management.module')),
            ],
        ),
    ]
