# Generated by Django 4.2.17 on 2024-12-28 04:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('management', '0002_registration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='registration',
            old_name='todaysDate',
            new_name='registration_time',
        ),
        migrations.RenameField(
            model_name='registration',
            old_name='student',
            new_name='user',
        ),
    ]
