# Generated by Django 4.2.17 on 2024-12-11 16:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itreporting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='issue',
            name='date_submitted',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
